version: '3.8'
services:
  my-service:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    image: my-service-image
    container_name: my-service-container
    ports:
      - "8080:8080"
