name: Java CD with Maven

on:
  pull_request_review:
    types:
      - submitted
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3 # Checkout the repository

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Copy Docker Compose file to remote host
        run: |
          echo "${{ secrets.PRODUCTION_SSH_KEY }}" > production_ssh_key.pem
          chmod 400 production_ssh_key.pem
          scp -o StrictHostKeyChecking=no -i production_ssh_key.pem docker-compose.yml ubuntu@3.85.63.41:~/docker-compose.yml

      - name: Execute Docker Compose file remotely
        run: |
          ssh -i production_ssh_key.pem -t ubuntu@3.85.63.41 "sudo docker compose -f ~/docker-compose.yml up -d"
