name: Java CI with Maven

on:
  push:
    branches: [ "development" ]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.tag_action.outputs.new_tag }}
    steps:
      - uses: actions/checkout@v3 # Checkout the repository
      - name: Bump version and push tag
        id: tag_action
        uses: anothrNick/github-tag-action@1.64.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: patch
          INITIAL_VERSION: 1.0.0

      - name: Bump version pom file
        run: mvn versions:set -DnewVersion=${{ steps.tag_action.outputs.new_tag }} -DgenerateBackupPoms=false

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build the container
        id: build
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/java-app:${{ steps.tag_action.outputs.new_tag }} .
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/java-app:${{ steps.tag_action.outputs.new_tag }} ${{ secrets.DOCKERHUB_USERNAME }}/java-app:latest

      - name: Run the container
        run: docker run --name java-app ${{ secrets.DOCKERHUB_USERNAME }}/java-app:${{ steps.tag_action.outputs.new_tag }}

      - name: Check output
        id: check_output
        run: |
          output=$(docker logs java-app)
          if [[ "$output" != *"Hello World!"* ]]; then
            exit 1
          fi

      - name: Push to Docker Hub
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/java-app:${{ steps.tag_action.outputs.new_tag }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/java-app:latest

      - name: Commit and push new pom version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add pom.xml
          git commit -m "Bump version to ${{ steps.tag_action.outputs.new_tag }}"
          git push

      - name: Update dependency graph
        uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6

  create_pull_request:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "master"
          github_token: ${{ secrets.GITHUB_TOKEN }}

  post-action:
    needs: build
    runs-on: ubuntu-latest
    if: failure()
    steps:
      - uses: actions/checkout@v3
      - name: Post-Action
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git push origin --delete ${{ needs.build.outputs.version }}
